name: Build And Upload

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:

    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
